// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.Data;

namespace SchoolManagement.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20190626083045_gcut")]
    partial class gcut
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolManagement.Data.School", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("Address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("City");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnName("Country");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnName("CreationTime");

                    b.Property<double>("Lattitude")
                        .HasColumnName("Lattitude");

                    b.Property<double>("Longitude")
                        .HasColumnName("Longitude");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnName("MobileNumber");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnName("ModificationTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasMaxLength(18);

                    b.Property<int>("PinCode");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnName("State");

                    b.HasKey("Id");

                    b.ToTable("SchoolInfos");
                });

            modelBuilder.Entity("SchoolManagement.Data.Staffinfo", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FacultyAddress")
                        .HasColumnName("address");

                    b.Property<string>("FacultyName")
                        .HasColumnName("Name")
                        .HasMaxLength(18);

                    b.Property<string>("Gender")
                        .HasColumnName("gender");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnName("MobileNumber");

                    b.Property<double>("Salary");

                    b.Property<string>("Subject")
                        .HasColumnName("subject");

                    b.HasKey("FacultyId");

                    b.ToTable("StaffInfos");
                });

            modelBuilder.Entity("SchoolManagement.Data.studentsinfo", b =>
                {
                    b.Property<long>("studentid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnName("address");

                    b.Property<string>("parentname")
                        .HasColumnName("parent");

                    b.Property<int>("rank")
                        .HasColumnName("rank");

                    b.Property<int>("standard")
                        .HasColumnName("standard");

                    b.Property<string>("studentname")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasMaxLength(18);

                    b.HasKey("studentid");

                    b.ToTable("StudentsInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
